#!/bin/bash
set -x
unzip DRIVE.zip
convert DRIVE/test/images/01_test.tif 01_test.ppm
convert DRIVE/test/images/02_test.tif 02_test.ppm
convert DRIVE/test/images/03_test.tif 03_test.ppm
convert DRIVE/test/images/04_test.tif 04_test.ppm
convert DRIVE/test/images/05_test.tif 05_test.ppm
convert DRIVE/test/images/06_test.tif 06_test.ppm
convert DRIVE/test/images/07_test.tif 07_test.ppm
convert DRIVE/test/images/08_test.tif 08_test.ppm
convert DRIVE/test/images/09_test.tif 09_test.ppm
convert DRIVE/test/images/10_test.tif 10_test.ppm
convert DRIVE/test/images/11_test.tif 11_test.ppm
convert DRIVE/test/images/12_test.tif 12_test.ppm
convert DRIVE/test/images/13_test.tif 13_test.ppm
convert DRIVE/test/images/14_test.tif 14_test.ppm
convert DRIVE/test/images/15_test.tif 15_test.ppm
convert DRIVE/test/images/16_test.tif 16_test.ppm
convert DRIVE/test/images/17_test.tif 17_test.ppm
convert DRIVE/test/images/18_test.tif 18_test.ppm
convert DRIVE/test/images/19_test.tif 19_test.ppm
convert DRIVE/test/images/20_test.tif 20_test.ppm
convert DRIVE/test/1st_manual/01_manual1.gif 01_manual1.pgm
convert DRIVE/test/1st_manual/02_manual1.gif 02_manual1.pgm
convert DRIVE/test/1st_manual/03_manual1.gif 03_manual1.pgm
convert DRIVE/test/1st_manual/04_manual1.gif 04_manual1.pgm
convert DRIVE/test/1st_manual/05_manual1.gif 05_manual1.pgm
convert DRIVE/test/1st_manual/06_manual1.gif 06_manual1.pgm
convert DRIVE/test/1st_manual/07_manual1.gif 07_manual1.pgm
convert DRIVE/test/1st_manual/08_manual1.gif 08_manual1.pgm
convert DRIVE/test/1st_manual/09_manual1.gif 09_manual1.pgm
convert DRIVE/test/1st_manual/10_manual1.gif 10_manual1.pgm
convert DRIVE/test/1st_manual/11_manual1.gif 11_manual1.pgm
convert DRIVE/test/1st_manual/12_manual1.gif 12_manual1.pgm
convert DRIVE/test/1st_manual/13_manual1.gif 13_manual1.pgm
convert DRIVE/test/1st_manual/14_manual1.gif 14_manual1.pgm
convert DRIVE/test/1st_manual/15_manual1.gif 15_manual1.pgm
convert DRIVE/test/1st_manual/16_manual1.gif 16_manual1.pgm
convert DRIVE/test/1st_manual/17_manual1.gif 17_manual1.pgm
convert DRIVE/test/1st_manual/18_manual1.gif 18_manual1.pgm
convert DRIVE/test/1st_manual/19_manual1.gif 19_manual1.pgm
convert DRIVE/test/1st_manual/20_manual1.gif 20_manual1.pgm
convert DRIVE/test/mask/01_test_mask.gif 01_test_mask.pgm
convert DRIVE/test/mask/02_test_mask.gif 02_test_mask.pgm
convert DRIVE/test/mask/03_test_mask.gif 03_test_mask.pgm
convert DRIVE/test/mask/04_test_mask.gif 04_test_mask.pgm
convert DRIVE/test/mask/05_test_mask.gif 05_test_mask.pgm
convert DRIVE/test/mask/06_test_mask.gif 06_test_mask.pgm
convert DRIVE/test/mask/07_test_mask.gif 07_test_mask.pgm
convert DRIVE/test/mask/08_test_mask.gif 08_test_mask.pgm
convert DRIVE/test/mask/09_test_mask.gif 09_test_mask.pgm
convert DRIVE/test/mask/10_test_mask.gif 10_test_mask.pgm
convert DRIVE/test/mask/11_test_mask.gif 11_test_mask.pgm
convert DRIVE/test/mask/12_test_mask.gif 12_test_mask.pgm
convert DRIVE/test/mask/13_test_mask.gif 13_test_mask.pgm
convert DRIVE/test/mask/14_test_mask.gif 14_test_mask.pgm
convert DRIVE/test/mask/15_test_mask.gif 15_test_mask.pgm
convert DRIVE/test/mask/16_test_mask.gif 16_test_mask.pgm
convert DRIVE/test/mask/17_test_mask.gif 17_test_mask.pgm
convert DRIVE/test/mask/18_test_mask.gif 18_test_mask.pgm
convert DRIVE/test/mask/19_test_mask.gif 19_test_mask.pgm
convert DRIVE/test/mask/20_test_mask.gif 20_test_mask.pgm

